name: Run Keploy API Tests

on:
  push:
    branches:
      - main

jobs:
  keploy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Keploy
        run: |
          curl -s https://keploy.io/install.sh | bash

      - name: Run Keploy tests
        run: |
          keploy test --delay 5
